name: format post pre-commit
run-name: ${{github.actor}} runs ${{github.workflow}} on ${{github.event_name}}
on:
    push:
        branches: [main, master]
    pull_request:
        branches: [main, master]
jobs:
    run-pytests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3
            - name: Set up Python 3.11.3
              uses: actions/setup-python@v4
              with:
                python-version: 3.11.3
                cache: pip
                cache-dependency-path: requirements.txt
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            - name: Test with pytest
              run: |
                pytest -v tests/test_helper.py
            - name: Run isort
              run: |
                isort --profile black .
            - name: Run black
              run: |
                black .
            - name: Run mypy
              run: |
                mypy .
